<?php
namespace Foo;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-30 at 14:22:12.
 */
class BarTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Bar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BarMock("Bla");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testVar1()
    {
        $this->assertEquals("Bla", $this->object->getVar1());
    }
}
